name: spcalc

services:
  run:
    image: spcalc:run
    pull_policy: build
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: runtime
    container_name: spcalc
    environment:
      - STAR_PATH_DATA_DIR=/app/data
    volumes:
      - ./data:/app/data:ro
      - ./cases:/app/cases
      - ./output:/app/output
    stdin_open: true  # Keep STDIN open (-i)
    tty: true  # Allocate a pseudo-TTY (-t)
