name: starpathcalculator

services:
  run:
    image: starpathcalculator:run
    pull_policy: build
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: runtime
    container_name: starpathcalculator
    environment:
      - STAR_PATH_DATA_DIR=/app/data
    volumes:
      - ./data:/app/data:ro
    stdin_open: true  # Keep STDIN open (-i)
    tty: true  # Allocate a pseudo-TTY (-t)
