[mypy]
strict = True
pretty = True
show_error_codes = True
show_column_numbers = False
show_error_context = True
ignore_missing_imports = False
disable_error_code = import-untyped

exclude = docker|tests|data|cases|utils
