[tox]
env_list = py312,py311,server-py312,server-py311
minversion = 4.0
requires = tox-uv

[testenv]
runner = uv-venv-lock-runner
dependency_groups = dev
change_dir = {toxinidir}
setenv =
    STAR_PATH_DATA_DIR = {toxinidir}/data
description = Run the tests with pytest
commands =
    pytest {tty:--color=yes} {posargs}

[testenv:py311]
runner = uv-venv-runner
base_python = python3.11
dependency_groups = dev
change_dir = {toxinidir}
setenv =
    STAR_PATH_DATA_DIR = {toxinidir}/data
description = Run tests with Python 3.11
commands =
    pytest {tty:--color=yes} {posargs}

[testenv:server-py312]
runner = uv-venv-runner
base_python = python3.12
dependency_groups = dev
change_dir = {toxinidir}
setenv =
    STAR_PATH_DATA_DIR = {toxinidir}/data
description = Run tests with the same versions as in the server
deps =
    great-circle-calculator==1.3.1
    juliandate==1.0.5
    matplotlib==3.9.2
    numpy==2.1.0
    pandas==2.2.2
    pytest==8.3.3
    skyfield==1.54
    tzfpy[tzdata]==1.3.1
commands =
    pytest {tty:--color=yes} {posargs}

[testenv:server-py311]
runner = uv-venv-runner
base_python = python3.11
dependency_groups = dev
change_dir = {toxinidir}
setenv =
    STAR_PATH_DATA_DIR = {toxinidir}/data
description = Run tests with the same versions as in the server
deps =
    great-circle-calculator==1.3.1
    juliandate==1.0.5
    matplotlib==3.9.2
    numpy==2.1.0
    pandas==2.2.2
    pytest==8.3.3
    skyfield==1.54
    tzfpy[tzdata]==1.3.1
commands =
    pytest {tty:--color=yes} {posargs}

[testenv:type]
runner = uv-venv-lock-runner
dependency_groups = dev
description = Run type checker via mypy
commands =
    mypy {posargs:spcalc/core}
