# -*- coding: utf-8 -*-
# tests/test_star_path_svg.py
import base64
import matplotlib
import numpy
from packaging.version import Version
from pathlib import Path
import platform
import pytest
import re
import skyfield

from starpathcalculator import __version__
from starpathcalculator.core.star_path import get_diagram

# Skip every test in this module
# pytestmark = pytest.mark.skip(reason="Cases are outdated, do not run")

print("\n=== SVG ===")
print(f"Package version: {__version__}")
print(f"python: {platform.python_version()}")
print(f"numpy: {numpy.__version__}, matplotlib: {matplotlib.__version__}")

if Version(numpy.__version__) < Version('2.0.0'):
    reference_svg_filename = 'cases/diagram_mpl3.5.2.svg'
    print(
        "Test cases: 0.1.0, python 3.10, numpy 2.2.3, matplotlib 3.5.2, skyfield 1.49"
    )
elif Version(skyfield.__version__) < Version('1.54'):
    reference_svg_filename = 'cases/diagram_mpl3.10.0.svg'
    print(
        "Test cases: 0.1.0, python 3.10, numpy 2.2.3, matplotlib 3.10.0, skyfield 1.49"
    )
else:
    # reference_svg_filename = 'cases/diagram_mpl3.10.8_skyfield1.54.svg'
    # print("Test cases: 0.1.0, python 3.12, numpy 2.4.4, matplotlib 3.10.8, skyfield 1.54")
    reference_svg_filename = 'cases/diagram_mpl3.10.8_skyfield1.54_0.1.1_docker.svg'
    print(
        "Test cases (docker): 0.1.1, python 3.12.3, numpy 2.4.4, matplotlib 3.10.8, skyfield 1.54"
    )


def normalize_svg_content(svg_content: str) -> str:
    """Normalizes SVG content by replacing specified elements and attributes."""
    # Ignore these elements
    svg_content = re.sub(
        r'<dc:date>[^<]+</dc:date>', '<dc:date> DATE </dc:date>', svg_content
    )
    svg_content = re.sub(
        r'<dc:title>[^<]+</dc:title>', '<dc:title> TITLE </dc:title>', svg_content
    )
    svg_content = re.sub(r'url\(#[a-z0-9]+\)', 'url(#URL)', svg_content)
    svg_content = re.sub(r'id="[a-z0-9]+"', 'id="ID"', svg_content)
    svg_content = re.sub(r'xlink:href="#[a-z0-9]+"', 'xlink:href="#HREF"', svg_content)
    svg_content = re.sub(
        r'(xlink:href="#DejaVuSans-.+") x="([^"]+)"',
        r'\1 transform="translate(\2 0)"',
        svg_content,
    )
    # Remove extra whitespace and normalize line endings
    svg_content = '\n'.join(line.strip() for line in svg_content.splitlines())

    return svg_content


with open(Path(__file__).parent.parent / reference_svg_filename, encoding='utf-8') as f:
    SVG_REF = normalize_svg_content(f.read())


test_input = {'year': -2000, 'month': 3, 'day': 1, 'lat': 40, 'lng': 116, 'tz_id': 'Asia/Shanghai', 'name': 'jupiter'}  # fmt: skip


@pytest.mark.parametrize("normalized_reference", [SVG_REF])
def test_get_svg(normalized_reference):
    """Tests the SVG generated by `get_diagram` by comparing it with a normalized reference SVG file."""
    res = get_diagram(**test_input)['svg_data']
    normalized_generated = normalize_svg_content(base64.b64decode(res).decode('utf-8'))

    assert normalized_generated == normalized_reference
